language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm test
  - sonar-scanner
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token 
  local_dir: build
  on:
    branch: master
notifications:
  slack: ingdesoftwarecorp:M517YaZr1TFeoN16omBIw6mB
 addons:
  sonarcloud:
    organization: "sebaarodas"
    token:
      secure: ${sonar-scanner}
    branches:
      - master
